#This is a basic github workflow
name: fastworkflow
#how the workflow will be triggered
on:
  push:
    branches: [main]

jobs:
  #this workflow contains the below jobs
  build:
    runs-on: ubuntu-latest
    #steps in the sequence
    steps: 
      #github provided action
      - uses: actions/checkout@v2
      #runsingle line comment
      - name: run one line script
        run: echo githubaction
      #run multiple comments
      - name: run multiline script
        run: |
          echo 1. what is the directory
          ls -la 
          echo
          echo 2. Is java installed
          java -version
          echo
          echo 3. Is git installed
          git --version
          echo
          echo 4. build tools
          mvn --version
          ant -version
          gradle --version
          echo 
          echo 5. who is running the script
          whoami
          echo 
          echo 6. disk layout
          df -h
          echo
          echo 7. env variables
          env
          echo
          